"""v0.8

Revision ID: 4b433da3a947
Revises: aa8c3bf3c8d2
Create Date: 2020-10-23 22:29:11.883634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b433da3a947'
down_revision = 'aa8c3bf3c8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resotre_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_expires', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('acc_to_restore', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acc_to_restore'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resotre_tokens')
    # ### end Alembic commands ###
