"""testoofof

Revision ID: 4ef8851e7a4e
Revises: 9b54629cc105
Create Date: 2020-10-19 02:27:06.786906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef8851e7a4e'
down_revision = '9b54629cc105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('masters_money', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('collected_m', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'collected_m')
    op.drop_column('ads', 'masters_money')
    # ### end Alembic commands ###
