"""testoofo

Revision ID: 9b54629cc105
Revises: 8f2cd6640f43
Create Date: 2020-10-19 01:18:33.508882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b54629cc105'
down_revision = '8f2cd6640f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_master', sa.Integer(), nullable=True))
    op.drop_column('users', 'referrals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrals', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'ref_master')
    # ### end Alembic commands ###
