"""v0.9

Revision ID: cfcd34a4490c
Revises: 4b433da3a947
Create Date: 2020-10-23 23:46:12.991360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfcd34a4490c'
down_revision = '4b433da3a947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restore_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_expires', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('acc_to_restore', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acc_to_restore'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resotre_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resotre_tokens',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date_expires', mysql.DATETIME(), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('acc_to_restore', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acc_to_restore'], ['users.id'], name='resotre_tokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('restore_tokens')
    # ### end Alembic commands ###
